### PR TITLE
Remove dependency on `related_projects`

### LINKED ISSUE #4655: /rest/v1/related_project/ endpoint performance
|  |  |
|-|-|
| Page | http://localhost/my-rsr/projects/:project_id/info  |
|  Time | 2,74s  |

### LINKED ISSUE #4969: [Hierarchies] FE Remove dependency on `related_projects`
In #4710, we remove the backend depedency on RelatedProjects, but the frontend does still depend on it.

# TODO

## Replace dependency on `RelatedProject`  in FE

The most likely candidates can be found by searching [`relatedProject`](https://github.com/akvo/akvo-rsr/search?l=JavaScript&q=relatedProject)

## Remove call to `related_projects` in FE

Currently it breaks the project editor

```
Uncaught (in promise) Error: Request failed with status code 404
    createError createError.js:16
    settle settle.js:17
    handleLoad xhr.js:62
    dispatchXhrRequest xhr.js:37
    xhrAdapter xhr.js:13
    dispatchRequest dispatchRequest.js:52
    promise callback*request Axios.js:61
    wrap bind.js:9
    get api.js:47
    fetchSet project-init-handler.js:43
    _callee$ project-init-handler.js:63
    Babel 10
    fetchSection project-init-handler.js:18
    fetchNextSection project-init-handler.js:69
    ProjectInitHandler project-init-handler.js:97
    React 6
    wrapped scheduler-tracing.development.js:207
    React 4
```

Probably the call in https://github.com/akvo/akvo-rsr/blob/master/akvo/rsr/spa/app/modules/editor/project-init-handler.js#L43

--------------

A related task might probably be #4934

### PR DESCRIPTION
**Pull request by MichaelAkvo**
# TODO / Done

Summarize what has been changed / what has to be done in order to finalize the PR.

 - [x] Remove `related_project` endpoint
 - [ ] Ensure the app works without `RelatedProjects`
 - [x] Add endpoint to add children to projects (for adding projects that "Contributes to") #5042
 - [x] Update `/v1/project` endpoint to accept setting parent contributing project #5042
 - [x] Set parent contributing project using `/v1/project` endpoint
 - [x] Return `Project.path` in `ProjectSerializer`

# Test plan

What tests are necessary to ensure this works or doesn't break anything working

 - [ ] Manual: Project editor should open
 

Closes #4969: [Hierarchies] FE Remove dependency on `related_projects`
Closes #4655: /rest/v1/related_project/ endpoint performance

### CODE REVIEW

**Comment by MichaelAkvo** [comment]
@ifirmawan using `/v1/project` you should now have `contributes_to_project` and `external_parent_iati_activity_id` as fields you can GET/POST. `contributes_to_project` takes the ID of another project and `external_parent_iati_activity_id` takes the IATI ID.

File: akvo/rsr/spa/app/modules/editor/reducer.js [hunk 1]
```diff
@@ -281,6 +275,28 @@ export default (state = initialState, action) => {
...
+    case actionTypes.SET_PARENT_PROJECT:
+      if (action.payload) {
+        const hasParent = ((state?.section1?.fields?.uuid) && (action.payload.uuid !== state.section1.fields.uuid))
+        return {
+          ...state,
+          section1: {
+            ...state?.section1,
+            fields: {
+              ...state?.section1?.fields,
+              contributesToProject: (!state?.section1?.fields?.contributesToProject && hasParent) ? action.payload.id : state?.section1?.fields?.contributesToProject
```
Comment (MichaelAkvo) [inline akvo/rsr/spa/app/modules/editor/reducer.js:293]: minor nitpick: this is a long line. If javascript allows it, maybe a linebreak or two would be good e.g
```js
condition ?
   trueTree : falseTree
```

File: akvo/rsr/spa/app/modules/editor/section1/comp/project-picker.jsx [hunk 2]
```diff
@@ -41,72 +60,66 @@ const ProjectPicker = ({ loading, projects, savedData, removeSetItem, hasImporte
...
         )}
         {!isExternal && (
           <Field
-            name="relatedProjects[0].relatedProjectName"
-            render={(nameProps) => {
+            name="contributesToProject"
+            render={({ input }) => {
+              const $options =
+                projects && projects.length > 0
+                  ? ((input.value && state.searchStr.length === 0) ? [projects.find(it => it.id === input.value)].filter(it => it != null).map(({ id, title }) => ({ value: id, label: `[${id}] ${title ? title : t('Untitled project')}` })) : state.options)
```
Comment (MichaelAkvo) [inline akvo/rsr/spa/app/modules/editor/section1/comp/project-picker.jsx:86]: I know this line probably isn't yours, but breaking it up would probably help, because double ternary statements are very difficult to read and it's way too long.

File: akvo/rsr/spa/app/modules/editor/section1/comp/project-picker.jsx [hunk 3]
```diff
@@ -41,72 +60,66 @@ const ProjectPicker = ({ loading, projects, savedData, removeSetItem, hasImporte
...
-                    )
-                  }}
-                />
+                <Select
+                  {...input}
+                  value={input.value}
+                  loading={loading}
+                  showSearch
+                  onSearch={filterOptions}
+                  notFoundContent={state.loading ? <Spin size="small" /> : (state.searchStr.length === 0 ? <span>{t('Start typing...')}</span> : <span>{t('No results')}</span>)}
```
Comment (MichaelAkvo) [inline akvo/rsr/spa/app/modules/editor/section1/comp/project-picker.jsx:95]: This is also too long and would benefit from linebreaks in order to be more readable.

File: akvo/rsr/spa/app/modules/editor/section1/section1.jsx [hunk 4]
```diff
@@ -139,8 +139,8 @@ const Info = ({ validations, fields, projectId, errors, showRequired, program, d
             />
             )}
           />
-            {!program && <ProjectPicker savedData={fields.relatedProjects[0]} projects={results && results.filter(it => it.id !== Number(projectId))} hasImportedResults={fields.hasImportedResults} {...{loading, projectId}} />}
-            {!fields.hasImportedResults && <ExternalProjects projectId={projectId} />}
+            {!program && <ProjectPicker projects={results && results.filter(it => it.id !== Number(projectId))} {...{ ...fields, loading, parentUuid }} />}
```
Comment (MichaelAkvo) [inline akvo/rsr/spa/app/modules/editor/section1/section1.jsx:142]: Why the double spread (`...`) ? :thinking:

File: akvo/rsr/spa/app/modules/editor/section5/section5.jsx [hunk 5]
```diff
@@ -577,6 +577,6 @@ export const customShouldUpdateSectionRoot = (prevProps, nextProps) => {
 }
 
 export default connect(
-  ({ editorRdr: { projectId, validations, showRequired, section5: { fields, errors }, section1: { fields: { relatedProjects, primaryOrganisation, allowIndicatorLabels, program, targetsAt } } } }) => ({ fields, relatedProjects, primaryOrganisation, projectId, allowIndicatorLabels, validations, errors, showRequired, program, targetsAt }),
+  ({ editorRdr: { projectId, validations, showRequired, section5: { fields, errors }, section1: { fields: { path, primaryOrganisation, allowIndicatorLabels, program, targetsAt } } } }) => ({ fields, path, primaryOrganisation, projectId, allowIndicatorLabels, validations, errors, showRequired, program, targetsAt }),
```
Comment (MichaelAkvo) [inline akvo/rsr/spa/app/modules/editor/section5/section5.jsx:580]: This line is way too long, imo and would benefit from being split up

File: akvo/rsr/spa/app/modules/editor/section4/section4.jsx [hunk 6]
```diff
@@ -94,7 +94,7 @@ const Desc = ({ fields, descriptionsOrder, projectId }) => {
                         </div>
                       )}
                     >
-                      <RTE {...input} index={index} validateStatus={validateStatus} />
+                      <RTE {...input} index={index} />
```
Comment (MichaelAkvo) [inline akvo/rsr/spa/app/modules/editor/section4/section4.jsx:97]: Why remove the `validateStatus` ?

Comment (ifirmawan) [reply akvo/rsr/spa/app/modules/editor/section4/section4.jsx:97]: because it's an unused property and I can't find validationStatus being used when i was digging into it by looking for ```this.props```

https://github.com/akvo/akvo-rsr/blob/feature/4969-hierarchies-fe-remove-dependency-on-related_projects/akvo/rsr/spa/app/utils/rte.jsx#L57

File: akvo/rsr/spa/app/modules/editor/section1/section1.jsx (hunk 4 above)
Comment (ifirmawan) [reply akvo/rsr/spa/app/modules/editor/section1/section1.jsx:142]: the first spread is used to ```loading, parentUuid, fields``` variables to make them pass in through the component with the same variable name.
the second spread is used to extract all props in the ```fields``` variable.

File: akvo/rsr/spa/app/modules/editor/reducer.js (hunk 1 above)
Comment (ifirmawan) [reply akvo/rsr/spa/app/modules/editor/reducer.js:293]: got it, Thanks @MichaelAkvo I'm working to fix it

File: akvo/rsr/spa/app/modules/editor/section1/comp/project-picker.jsx (hunk 2 above)
Comment (ifirmawan) [reply akvo/rsr/spa/app/modules/editor/section1/comp/project-picker.jsx:86]: All right, working on it

File: akvo/rsr/spa/app/modules/editor/section1/section1.jsx (hunk 4 above)
Comment (MichaelAkvo) [reply akvo/rsr/spa/app/modules/editor/section1/section1.jsx:142]: `{ ...fields, loading, parentUuid }` should be sufficient

File: akvo/rsr/spa/app/modules/editor/reducer.js [hunk 7]
```diff
@@ -147,15 +149,9 @@ export default (state = initialState, action) => {
       newState.backendError = null
       const { setName } = action
       const itemIndex = action.itemIndex !== undefined ? action.itemIndex : get(newState[sectionKey].fields, `${action.setName}`).length - 1
-      let updatedItem = {
+      const updatedItem = {
         ...get(newState[sectionKey].fields, `${setName}[${itemIndex}]`)
```
Comment (navins94) [inline akvo/rsr/spa/app/modules/editor/reducer.js:153]: Better to add optional chaining here

File: akvo/rsr/spa/app/modules/editor/section1/comp/external-projects.jsx [hunk 8]
```diff
@@ -1,60 +1,45 @@
...
-    api.delete(`/project/${projectId}/external_project/${project.id}/`)
-    setProjects(projects.filter(it => it.id !== project.id))
+    api.delete(`/project/${params?.id}/external_project/${project.id}/`)
+      .then(() => removeExternalProject(project))
+      .catch(() => message.error('Failed to remove external project'))
   }
   return (
     <div className="external-projects">
-      {projects.length > 0 && (
+      {externalProjects.length > 0 && (
```
Comment (navins94) [inline akvo/rsr/spa/app/modules/editor/section1/comp/external-projects.jsx:39]: Better to add optional chaining here as well

File: akvo/rsr/spa/app/modules/editor/section1/comp/external-projects.jsx [hunk 9]
```diff
@@ -1,60 +1,45 @@
...
         <div className="ant-row ant-form-item projects-list">
           <div className="ant-col ant-form-item-label"><label>{t('External child projects')}</label></div>
-          {projects.map((project) =>
+          {externalProjects.map((project) =>
```
Comment (navins94) [inline akvo/rsr/spa/app/modules/editor/section1/comp/external-projects.jsx:42]: Better to add optional chaining here as well

File: akvo/rsr/spa/app/modules/editor/section1/section1.jsx [hunk 10]
```diff
@@ -70,6 +70,7 @@ const Info = ({ validations, fields, projectId, errors, showRequired, program, d
     }
   }, [fields.title])
   const disableMWCFields = fields?.program?.id === 9062
+  const projects = results && results.filter(it => it.id !== Number(projectId))
```
Comment (navins94) [inline akvo/rsr/spa/app/modules/editor/section1/section1.jsx:73]: I think you can remove results check and just add optional chaining

Comment (ifirmawan) [reply akvo/rsr/spa/app/modules/editor/section1/section1.jsx:73]: noted @navins94 will do, Thank you

**Review by navins94 — APPROVED** [review]
